### ISSUE TITLE
为什么运行gosk.exe run没有生成模板

### ISSUE THREAD

**Issue by icngor** [scottkiss/gosk#5]
操作步骤：
* go get 此项目
* cd 项目/bin
* go build gosk.go （go build）
* ./gosk.exe run
* 访问localhost
* 显示_404 page not found_

**Comment by scottkiss** [comment]
@icngor  你缺少一步骤。go build gosk.go 之后，需要执行gosk.exe build ---编译生成页面,然后再gosk.exe run
